# Generated by Django 5.2.12 on 2026-04-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewkit",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Startup", "Startup"),
                    ("Mid-size", "Mid-size"),
                    ("Enterprise", "Enterprise"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="interviewkit",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tech", "Tech"),
                    ("Finance", "Finance"),
                    ("Healthcare", "Healthcare"),
                    ("Marketing", "Marketing"),
                    ("Operations", "Operations"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="interviewkit",
            name="remote_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remote", "Remote"),
                    ("Hybrid", "Hybrid"),
                    ("On-site", "On-site"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="interviewkit",
            name="role_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Junior", "Junior"),
                    ("Mid-level", "Mid-level"),
                    ("Senior", "Senior"),
                    ("Lead", "Lead"),
                ],
                max_length=50,
            ),
        ),
    ]
